spring:
  session:
    store-type: none
  profiles:
    application:
        name: freamwork
  freemarker:
      template-loader-path: classpath:/templates/views
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      suffix: .json.ftl
      request-context-attribute: request
      expose-spring-macro-helpers: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      "hibernate.cache.use_second_level_cache": "false"
      "hibernate.cache.use_query_cache": "true"
      "hibernate.cache.region.factory_class": "org.hibernate.cache.ehcache.EhCacheRegionFactory"
## 数据库访问配置
  datasource:
    url: jdbc:mysql://10.0.0.20:3306/hardware?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
## 连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 超时时间
    maxWait: 60000

    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000

    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${publicKey}
server:
  port: 8080
# java -cp druid-1.0.29.jar com.alibaba.druid.filter.config.ConfigTools 1234
privateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAp4TF8PO2xO3zDchq1ty2wsG9B78hQt6mqiKHHJVq2jkBT86pzpFs8gUoTWD8/6cBXJ07rF2qA52kNprmJPO7ewIDAQABAkAfsg+Bt5stR5hlUzZj0P8DeoS5ooA4lsgSCNZnoh3FjBSoMP42JBoaDmOuIib5DcrHFo1FTlHUDVvbHz0KmLGBAiEA6rzWncuADHYvgjCTlazsN4SMYwWwo5WlsG5dqgqn6L0CIQC2sT3xcFtdN/FxVSrHi8buaLg616eXuPf0RIqxKgiElwIhAK510vxL9stMO1sDR20CrD1G4h/mZrXtzssl+68ZZFnxAiAwjJlxd/JPq3Y2L/PWY4bSBHIw8O5Qm48JEs3olsr8sQIgXfV2emIMkiGQEFF23FfSTDLLEFKNM9GjGb4SwC54RPU=
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKeExfDztsTt8w3IatbctsLBvQe/IULepqoihxyVato5AU/Oqc6RbPIFKE1g/P+nAVydO6xdqgOdpDaa5iTzu3sCAwEAAQ==
password: eJl8Ww/jV9oio9evhnP5KMuqHblRwIK8hitR1uTh+1hiltI45jC64YSgMucRefnXa1N5NeociBGjWZv640IdqA==
