spring:
  profiles:
    active: @profileActive@
    application:
        name: freamwork
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
server:
  port: 80
# java -cp druid-1.0.29.jar com.alibaba.druid.filter.config.ConfigTools 1234
privateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAp4TF8PO2xO3zDchq1ty2wsG9B78hQt6mqiKHHJVq2jkBT86pzpFs8gUoTWD8/6cBXJ07rF2qA52kNprmJPO7ewIDAQABAkAfsg+Bt5stR5hlUzZj0P8DeoS5ooA4lsgSCNZnoh3FjBSoMP42JBoaDmOuIib5DcrHFo1FTlHUDVvbHz0KmLGBAiEA6rzWncuADHYvgjCTlazsN4SMYwWwo5WlsG5dqgqn6L0CIQC2sT3xcFtdN/FxVSrHi8buaLg616eXuPf0RIqxKgiElwIhAK510vxL9stMO1sDR20CrD1G4h/mZrXtzssl+68ZZFnxAiAwjJlxd/JPq3Y2L/PWY4bSBHIw8O5Qm48JEs3olsr8sQIgXfV2emIMkiGQEFF23FfSTDLLEFKNM9GjGb4SwC54RPU=
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKeExfDztsTt8w3IatbctsLBvQe/IULepqoihxyVato5AU/Oqc6RbPIFKE1g/P+nAVydO6xdqgOdpDaa5iTzu3sCAwEAAQ==
password: eJl8Ww/jV9oio9evhnP5KMuqHblRwIK8hitR1uTh+1hiltI45jC64YSgMucRefnXa1N5NeociBGjWZv640IdqA==
